# yaml-language-server: $schema=https://storage.googleapis.com/coderabbit_public_assets/schema.v2.json

# The following configurations override Teamworks organization settings
reviews:
  profile: chill
  review_status: false
  auto_review:
    drafts: false
