default_language_version:
  python: python3.12
files: .*\.py
repos:
  - repo: local
    hooks:
      - id: update-ruff-configuration
        name: Update Ruff Configuration
        entry: |
          /bin/bash -c '
          curl -o "$HOME/.ruff.toml" "https://raw.githubusercontent.com/Teamworksapp/ruff-config/refs/heads/main/ruff.toml"
          curl -o "$HOME/.ruff.sh" "https://raw.githubusercontent.com/Teamworksapp/ruff-config/refs/heads/main/ruff.sh"
          chmod +x "$HOME/.ruff.sh"
          '
        language: system
        types: [bash]
        always_run: true
      - id: ruff-common
        name: Ruff Common
        language: script
        entry: /bin/bash -c "$HOME/.ruff.sh"
        always_run: true